name: 'Build Debian ISO'

on:
  workflow_dispatch:

env:
  SOURCE: debian-12.5.0-amd64-DVD-1.iso
  TARGET: debian-12.5.0-amd64-unattended.iso
  ARCH: amd64
  LABEL: debian
  TMP: "tempdir"

jobs:
  build-debian-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: make install-depends
      - name: Download ISO
        run: curl -LOs https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/${SOURCE}
      - name: Make ISO
        run: make image 
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LABEL }}-${{ env.ARCH }}-iso
          path: ${{ env.TARGET }}
          overwrite: true
  release:
    runs-on: ubuntu-latest
    needs: build-debian-iso
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.LABEL }}-${{ env.ARCH }}-iso
          path: ${{ env.TARGET }}
      - name: Generate checksum
        run: ls -laths && ls -laths ${{ env.TARGET }}/ && sha256sum ${{ env.TARGET }} > ${{ env.TARGET }}.sha256
      - name: Split file into 1GB slices
        run: split -b 1G ${{ env.TARGET }} ${{ env.TARGET }}.
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest release"
          files: |
            ${{ env.TARGET }}.*
